### PR TITLE
Allow wait instead of cancel

### PR DESCRIPTION
**Pull request by haard**
I've muddled through a solution that Works For Me for #10 - I'm not primarily a JS dev and have never done anything with Github Actions before, so YMMV...

### CODE REVIEW

**Comment by joeyparis** [comment]
@haard what are your thoughts on also adding a max_timeout option to stop polling after a period of time and just canceling the action?

**Comment by haard** [comment]
That sounds like a good idea; I'll not have time to look at it myself until the weekend at the earliest though.

**Comment by joeyparis** [comment]
No worries, definitely not time critical for me!

**Comment by joshgubler** [comment]
GitHub Actions now supports this natively. https://docs.github.com/en/actions/using-jobs/using-concurrency

**Pull request closed without merging**
